# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0003_auto_20171024_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='latitude',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='longitude',
            field=models.CharField(max_length=10),
        ),
    ]
