# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:24
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quedadas', '0006_auto_20171024_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snippets',
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
