# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0008_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='answer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='question',
            field=models.CharField(max_length=100),
        ),
    ]
