# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 10:54
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quedadas', '0015_remove_tracking_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='averagespeed',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='calories',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='distance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='steps',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracking',
            name='totalTimeMillis',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
