# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-14 10:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quedadas', '0016_auto_20171114_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='meeting',
        ),
        migrations.AddField(
            model_name='meeting',
            name='tracking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting',
                                    to='quedadas.Tracking'),
        ),
    ]
