# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 16:29
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quedadas', '0018_auto_20171114_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='tracking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meeting',
                                       to='quedadas.Tracking'),
        ),
    ]
