# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0022_auto_20171124_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='last_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.TextField(default='no message'),
            preserve_default=False,
        ),
    ]
