# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-24 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quedadas', '0023_auto_20171124_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='username_message',
            field=models.TextField(null=True),
        ),
    ]
