# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0027_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challengedBase',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='creatorBase',
            field=models.FloatField(null=True),
        ),
    ]
