# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0029_auto_20171130_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='last_message',
            new_name='lastMessage',
        ),
        migrations.AlterField(
            model_name='chat',
            name='listUsersChat',
            field=models.ManyToManyField(related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
