# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quedadas', '0030_auto_20171130_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='maxAverageSpeed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='maxDistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='maxDuration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='minAverageSpeed',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='minDistance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='statistics',
            name='minDuration',
            field=models.IntegerField(default=0),
        ),
    ]
