# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-01 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('quedadas', '0031_auto_20171130_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
