# Generated by Django 2.0 on 2017-12-04 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0032_profile_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendship',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='lastTracking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='quedadas.Tracking'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='maxDistance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='minDistance',
            field=models.FloatField(default=0),
        ),
    ]
