# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-02 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0033_friendship_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='maxDistance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='minDistance',
            field=models.FloatField(default=0),
        ),
    ]
