# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-06 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0033_auto_20171206_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
