# Generated by Django 2.0 on 2017-12-31 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0033_auto_20171212_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('distance', models.IntegerField(blank=True, default=0)),
                ('zip', models.CharField(max_length=5, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='chat',
            name='meeting',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_r', to='quedadas.Meeting'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='postal_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='quedadas.Zone'),
        ),
    ]
