# Generated by Django 2.0 on 2017-12-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0034_auto_20171231_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='average',
            field=models.FloatField(default=0),
        ),
    ]
