# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-08 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0034_challenge_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='lastMessage',
            field=models.TextField(blank=True),
        ),
    ]
