# Generated by Django 2.0 on 2017-12-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0035_zone_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='level',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
