# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-11 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quedadas', '0038_auto_20180109_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ban_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='ban_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
